CREATE TABLE Visa_From_Issue (
VisaID VARCHAR(100) PRIMARY KEY,
VisaType VARCHAR(100),
ApplicationID VARCHAR(100) NOT NULL,
ECID VARCHAR(100) NOT NULL,
IssueDate DATE,
FOREIGN KEY (ApplicationID)
    REFERENCES Application
    ON DELETE SET DEFAULT
FOREIGN KEY (ECID)
    REFERENCES Embassy_Consulates
    ON DELETE SET DEFAULT
);

CREATE TABLE Asylum_Refugee_Visa (
VisaID VARCHAR(100) PRIMARY KEY,
Reason VARCHAR(100) NOT NULL,
FOREIGN KEY (VisaID)
REFERENCES Visa_&_From_&_Issue
    ON DELETE CASCADE
);


CREATE TABLE Travel_History_Records_Travels_By (
RecordID VARCHAR(100) PRIMARY KEY,
Time TIME NOT NULL,
Date DATE NOT NULL,
Destination VARCHAR(100) NOT NULL,
Departure VARCHAR(100) NOT NULL,
VisaID VARCHAR(100) NOT NULL,
FOREIGN KEY (Destination, Departure)
REFERENCES In/Out(Destination, Departure)
ON DELETE NO ACTION
);


CREATE TABLE Applicants (
ApplicantID VARCHAR(100) PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Nationality VARCHAR(100) NOT NULL,
DateOfBirth DATE NOT NULL,
FOREIGN KEY (DateOfBirth)
REFERENCES DateOfBirth_&_Age
);
